# Generated by Django 3.0.3 on 2020-04-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='sender',
            new_name='sender_mail',
        ),
        migrations.AddField(
            model_name='email',
            name='sender_name',
            field=models.CharField(default='nan', max_length=50),
            preserve_default=False,
        ),
    ]
