# Generated by Django 3.0.3 on 2020-04-01 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20200401_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='title',
        ),
    ]
