# Generated by Django 3.0.3 on 2020-04-02 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_remove_email_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
